# Generated by Django 4.2 on 2023-04-28 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0002_seller_created_by_seller_created_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Coloured', 'Coloured'), ('BlackAndWhite', 'BlackAndWhite')], max_length=64)),
                ('expiry_year', models.DateTimeField(blank=True, null=True)),
                ('company', models.CharField(choices=[('Samsung', 'Samsung'), ('Kodak', 'Kodak'), ('Ilford', 'Ilford')], max_length=64)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('exposures', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_created_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_modified_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('PointAndShoot', 'PnS'), ('RangeFinder', 'RangeFinder'), ('SLR', 'slr')], max_length=64)),
                ('lens', models.CharField(max_length=255)),
                ('battery_type', models.CharField(max_length=255)),
                ('company', models.CharField(choices=[('Yashica', 'Yashica'), ('Pentax', 'Pentax'), ('Nikon', 'Nikon'), ('Canon', 'Canon'), ('Samsung', 'Samsung')], max_length=64)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_created_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_modified_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
