# Generated by Django 4.2 on 2023-04-28 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_camera_id_alter_film_id_alter_seller_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='selling_price',
        ),
    ]
