# Generated by Django 4.2 on 2023-04-28 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0005_remove_stock_selling_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.TextField()),
                ('email', models.CharField(max_length=128)),
                ('social_media_handle', models.CharField(max_length=128)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_created_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_modified_%(class)s_related', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sold_on', models.DateTimeField(blank=True, null=True)),
                ('medium', models.CharField(choices=[('Instagram', 'Instagram'), ('Other', 'Other')], default='Instagram', max_length=128)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_created_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_modified_%(class)s_related', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stock')),
                ('sold_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.buyer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
